openapi: 3.0.0
info:
  title: API de Produtos
  description: API para gerenciar produtos.
  version: 1.0.0

paths:
  # Categoria: Produtos
  /api/products:
    post:
      summary: Cadastrar produto
      description: Cria um novo produto no sistema.
      tags:
        - Produtos
      requestBody:
        description: Dados do produto para criação
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - description
                - price
                - category
              properties:
                name:
                  type: string
                description:
                  type: string
                price:
                  type: number
                category:
                  type: string
                  enum:
                    - LANCHE
                    - ACOMPANHAMENTO
                    - BEBIDA
                    - SOBREMESA
      responses:
        '201':
          description: Produto criado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  description:
                    type: string
                  price:
                    type: number
                  category:
                    type: string
        '400':
          description: Dados inválidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Erro interno do servidor

  /api/products/{id}:
    put:
      summary: Atualizar produto
      description: Atualiza as informações de um produto pelo ID.
      tags:
        - Produtos
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        description: Dados do produto para atualização
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - description
                - price
                - category
              properties:
                name:
                  type: string
                description:
                  type: string
                price:
                  type: number
                category:
                  type: string
                  enum:
                    - LANCHE
                    - ACOMPANHAMENTO
                    - BEBIDA
                    - SOBREMESA
      responses:
        '200':
          description: Produto atualizado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  description:
                    type: string
                  price:
                    type: number
                  category:
                    type: string
        '400':
          description: Dados inválidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Erro interno do servidor

    delete:
      summary: Remove produto
      description: Remove um produto do sistema pelo ID.
      tags:
        - Produtos
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Produto removido com sucesso
        '400':
          description: Dados inválidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Erro interno do servidor

    get:
      summary: Busca produto por id
      description: Retorna os dados de um produto por id.
      tags:
        - Produtos
      parameters:
        - in: path
          name: id
          required: true
      responses:
        '200':
          description: Produto encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  description:
                    type: string
                  price:
                    type: number
                  category:
                    type: string
        '400':
          description: Dados inválidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Erro interno do servidor

  /api/products/category/{category}:
    get:
      summary: Listar produtos por categoria
      description: Retorna a lista de produtos de uma categoria específica.
      tags:
        - Produtos
      parameters:
        - in: path
          name: category
          required: true
          schema:
            type: string
            enum:
              - LANCHE
              - ACOMPANHAMENTO
              - BEBIDA
              - SOBREMESA
      responses:
        '200':
          description: Produtos encontrados
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    description:
                      type: string
                    price:
                      type: number
                    category:
                      type: string
        '400':
          description: Dados inválidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Erro interno do servidor
    